import type { Metadata } from "next";
import "./globals.css";

import { Space_Grotesk, Inter, IBM_Plex_Mono } from "next/font/google";

import { Toaster } from "sonner";

import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryProvider } from "@/providers/query-provider";

import { cn } from "@/lib/utils";

const display = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
});
const body = Inter({ subsets: ["latin"], variable: "--font-body" });
const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(display.variable, body.variable, mono.variable)}
    >
      <body>
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <TooltipProvider>
              <div className="min-h-full flex flex-col">{children}</div>
            </TooltipProvider>
          </ThemeProvider>
        </QueryProvider>

        <Toaster richColors />
      </body>
    </html>
  );
}

